name: ngpack
description: A simple command-line application to list or extract files from ggpack files.
version: 0.0.6
homepage: https://github.com/scemino/ngpack

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  glob: ^2.0.0
  path: ^1.8.0
  universal_io: ^2.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.7
